# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce711d9cf60e5ee118e047ae1e61dd2f29339cc934d488b0fdaf4b851d9c400864b83909491ca89ab1f685a3525a76acdf9d62ac6d03314d1d87bbd167ba5695

test:
  secret_key_base: e6b454e020f3ad45f9860f395e6b4a17282dcf5f7a5094229e05509a4aba9ae28b6cc6ba1a0820149824f1e29d057d3a36069c19bd4e4448220802fae7e5cf2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
